### ISSUE TITLE
Release latest version of npm?

### ISSUE THREAD

**Issue by deathcap** [sjmulder/nbt-js#10]
The 0.3.0 release on https://www.npmjs.com/package/nbt is a bit old compared to source in git, could a new version be released from the latest master? (`npm version`, `npm publish`)?

@sjmulder 

p.s. if you're looking for a maintainer, I'd be willing to help

**Comment by sjmulder** [comment]
Sorry for this to have taken so long, I got a bit sidetracked with new career.

I've addressed some of the outstanding issues, cleaned up a bit and published 0.4.0.

As for the maintainership, are you still serious about that? Your repo looks rather inactive, like mine. If you have some improvements to offer I'll be happy to swiftly accept pull requests. Then if you have longer term interest in maintainer ship we can transfer the npm ownership and all that.

I'm closing this issue as the release itself is done, let's discuss the above further in your repo issue or a new issue here.

Cheers
