### ISSUE TITLE
nbt.Reader.byte() should be unsigned

### ISSUE THREAD

**Issue by polarstoat** [sjmulder/nbt-js#21]
I'm parsing Minecraft world data and occasionally get unexpected results for block IDs (which are 0-255). I tried changing `nbt.Reader.byte()` to use `Buffer.readUInt8` instead of `Buffer.readInt8` and the behaviour was then as expected.

If Minecraft is only storing unsigned integers with the NBT byte tag, I think it'd be safe to assume the byte tag is only intended to store unsigned integers.

**Comment by sjmulder** [comment]
That makes sense to me. How about other integer type? Perhaps there should be pairs of methods for signed and unsigned for all.

**Comment by polarstoat** [comment]
Minecraft stores coordinates as `TAG_Int`, so that would need to remain signed. I don't know if it stores signed values as `TAG_Short`.

Perhaps. IMO, I'd stick with the 11 methods in [the NBT spec](http://wiki.vg/NBT#Specification).

**Comment by sjmulder** [comment]
Sorry to have taken so long, but I looked at the spec again and there it’s quite clear that TAG_Byte is signed. If unsigned bytes are used often in practice we could add another method for it. Do you find that reasonable?

**Comment by polarstoat** [comment]
Yes, that sounds like a good idea.

**Comment by sjmulder** [comment]
Thanks for bringing this up and thinking along on the solution. Implemented in the commit above.
